site_name: "shellm template"
site_description: "Copier template for shellm projects"
site_url: "https://shellm-org.github.io/template"
repo_url: "https://github.com/shellm-prg/template"
repo_name: "shellm-org/template"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Home:
  - Overview: index.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - License: license.md
- Usage:
  - Requirements: requirements.md
  - Generating a project: generate.md
  - Working on a project: work.md
  - Updating a project: update.md
- Author's website: https://pawamoy.github.io/

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

markdown_extensions:
- admonition
- callouts
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/mastodon
    link: https://fosstodon.org/@pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
  - icon: fontawesome/brands/gitter
    link: https://app.gitter.im/#/room/#shellm-org/community:gitter.im

extra_css:
- css/custom.css
